---
networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

volumes:
  unbound:
  wireguard-config:
  db:
  wireguard-ui-config:
  etc-pihole:
  etc-dnsmasq.d:


services:
  unbound:
    image: ${UNBOUND_IMAGE}
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    volumes:
      - unbound:/opt/unbound/etc/unbound/
    networks:
      private_network:
        ipv4_address: 10.2.0.200
    cap_add:
      - NET_ADMIN
    env_file: .env
  
  wireguard:
    depends_on:
      - unbound
      - pihole
    image: linuxserver/wireguard
    container_name: wireguard
    ports:
      - 5000:5000
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - wireguard-config:/config
    env_file: .env

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - db:/app/db
      - wireguard-ui-config:/config
    env_file: .env

  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    ports:
      - 80:80/tcp
    dns:
      - 127.0.0.1
      - ${PIHOLE_DNS}
    volumes:
      - etc-pihole:/etc/pihole/
      - etc-dnsmasq.d:/etc/dnsmasq.d/
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    networks:
      private_network:
        ipv4_address: 10.2.0.100
    environment:
      TZ: America/New_York
      TEMPERATUREUNIT: f
      WEBTHEME: 'default-dark'
    env_file: .env
